# Generated by Django 2.1.7 on 2019-02-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190220_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='centro_custo',
            field=models.IntegerField(unique=True),
        ),
    ]
