# Generated by Django 2.1.7 on 2019-02-14 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_serv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposervico',
            name='dt_criacao',
        ),
        migrations.AddField(
            model_name='tiposervico',
            name='tipo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
