# Generated by Django 2.1.7 on 2019-02-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrdemServico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposerico',
            options={'verbose_name': 'Tipo de serviço'},
        ),
    ]
