# Generated by Django 2.1.7 on 2019-02-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrdemServico', '0004_auto_20190214_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposervico',
            options={'verbose_name': 'Tipos de serviço'},
        ),
    ]
