# Generated by Django 2.1.7 on 2019-02-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOrdemServico', '0005_auto_20190214_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=220)),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOrdemServico.TipoServico')),
            ],
        ),
    ]
