# Generated by Django 2.1.7 on 2019-02-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOrdemServico', '0006_ordemservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOrdemServico.TipoServico'),
        ),
    ]
