# Generated by Django 2.1.7 on 2019-02-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOrdemServico', '0007_auto_20190214_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'verbose_name': 'Ordens de seriço'},
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOrdemServico.TipoServico'),
        ),
    ]
